"""Remove username from Employee

Revision ID: 146704bf8c9b
Revises: 1f2f0aea1772
Create Date: 2025-07-14 14:43:43.298412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '146704bf8c9b'
down_revision = '1f2f0aea1772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
