"""initial migration

Revision ID: 1f2f0aea1772
Revises: 
Create Date: 2025-07-14 13:24:09.920638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f2f0aea1772'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('supervisors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('middle_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('doj', sa.Date(), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=False),
    sa.Column('employee_code', sa.String(length=50), nullable=False),
    sa.Column('esic_no', sa.String(length=50), nullable=True),
    sa.Column('uan_no', sa.String(length=50), nullable=True),
    sa.Column('aadhaar_no', sa.String(length=12), nullable=False),
    sa.Column('pan_no', sa.String(length=10), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('ifsc', sa.String(length=11), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('profile_image', sa.String(length=200), nullable=True),
    sa.Column('aadhaar_image', sa.String(length=200), nullable=True),
    sa.Column('pan_image', sa.String(length=200), nullable=True),
    sa.Column('passbook_image', sa.String(length=200), nullable=True),
    sa.Column('current_address', sa.Text(), nullable=False),
    sa.Column('permanent_address', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supervisor_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('middle_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('employee_code', sa.String(length=50), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('doj', sa.Date(), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=False),
    sa.Column('aadhaar_no', sa.String(length=12), nullable=False),
    sa.Column('pan_no', sa.String(length=10), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('ifsc', sa.String(length=11), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('profile_image', sa.String(length=200), nullable=True),
    sa.Column('aadhaar_image', sa.String(length=200), nullable=True),
    sa.Column('pan_image', sa.String(length=200), nullable=True),
    sa.Column('passbook_image', sa.String(length=200), nullable=True),
    sa.Column('current_address', sa.Text(), nullable=False),
    sa.Column('permanent_address', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['supervisors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ot_hours', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('attendance')
    op.drop_table('employees')
    op.drop_table('supervisors')
    op.drop_table('users')
    op.drop_table('locations')
    # ### end Alembic commands ###
