"""Add overtime_hours column to attendance table

Revision ID: b5b9f0876b66
Revises: 7ab94f5e153e
Create Date: 2025-07-20 19:21:29.189793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5b9f0876b66'
down_revision = '7ab94f5e153e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overtime_hours', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('overtime_hours')

    # ### end Alembic commands ###
